"""
run_agent.py — CLI entry point for the AML Investigation Agent.

Usage:
    python run_agent.py --alert ALT-001
    python run_agent.py --alert ALT-003 --thread-id custom-thread-123
    python run_agent.py --list-alerts
"""

import argparse
import json
import os
import sys
from dotenv import load_dotenv

load_dotenv()

# Disable LangSmith tracing if no API key is configured
if not os.getenv("LANGCHAIN_API_KEY") or os.getenv("LANGCHAIN_API_KEY", "").startswith("ls__..."):
    os.environ["LANGCHAIN_TRACING_V2"] = "false"


# ── Alert registry ─────────────────────────────────────────────────────────────
# These are the seed alert IDs generated by data/seed_data.py.
ALERT_REGISTRY = {
    "ALT-001": "STRUCTURING",
    "ALT-002": "VELOCITY_ANOMALY",
    "ALT-003": "HIGH_RISK_JURISDICTION",
    "ALT-004": "PEP_COUNTERPARTY",
    "ALT-005": "ADVERSE_MEDIA",
}


def list_alerts() -> None:
    print("\nAvailable alert scenarios:\n")
    print(f"  {'Alert ID':<12} {'Rule':<30} {'Expected Route'}")
    print(f"  {'-'*12} {'-'*30} {'-'*30}")
    expected = {
        "ALT-001": "Human review",
        "ALT-002": "Human review",
        "ALT-003": "Human review → SAR",
        "ALT-004": "Human review → SAR",
        "ALT-005": "Auto-clear or human review",
    }
    for alert_id, rule in ALERT_REGISTRY.items():
        print(f"  {alert_id:<12} {rule:<30} {expected[alert_id]}")
    print()


def run(alert_id: str, thread_id: str | None = None) -> None:
    if alert_id not in ALERT_REGISTRY:
        print(f"\nError: unknown alert ID '{alert_id}'")
        print("Run with --list-alerts to see available scenarios.\n")
        sys.exit(1)

    # Lazy import — allows the scaffold to be tested before agent code exists.
    try:
        from agent.graph import build_graph
        from data.seed_data import load_alert
    except ImportError as e:
        print(f"\nAgent not yet built: {e}")
        print("This is expected at scaffold stage. Build Components 2–5 first.\n")
        sys.exit(0)

    thread_id = thread_id or alert_id
    config = {"configurable": {"thread_id": thread_id}}

    print(f"\n{'='*60}")
    print(f"  AML Investigation Agent")
    print(f"  Alert: {alert_id}  |  Rule: {ALERT_REGISTRY[alert_id]}")
    print(f"  Thread: {thread_id}")
    print(f"{'='*60}\n")

    alert = load_alert(alert_id)
    graph = build_graph()

    final_state = None
    for step in graph.stream({"alert": alert}, config=config):
        node_name = list(step.keys())[0]
        print(f"  ✓ {node_name}")

    # Retrieve final state from checkpointer
    snapshot = graph.get_state(config)
    final_state = snapshot.values

    print(f"\n{'='*60}")
    print(f"  Decision: {final_state.get('decision', 'pending')}")
    print(f"{'='*60}\n")

    print(json.dumps(final_state, indent=2, default=str))


def main() -> None:
    parser = argparse.ArgumentParser(
        description="AML Suspicious Activity Investigation Agent"
    )
    parser.add_argument(
        "--alert",
        type=str,
        help="Alert ID to investigate (e.g. ALT-001)",
    )
    parser.add_argument(
        "--thread-id",
        type=str,
        default=None,
        help="LangGraph thread ID for checkpointing (defaults to alert ID)",
    )
    parser.add_argument(
        "--list-alerts",
        action="store_true",
        help="List all available alert scenarios and exit",
    )

    args = parser.parse_args()

    if args.list_alerts:
        list_alerts()
        return

    if not args.alert:
        parser.print_help()
        sys.exit(1)

    run(args.alert, args.thread_id)


if __name__ == "__main__":
    main()
